# Generated by Django 5.0.6 on 2024-06-02 09:15

from django.db import migrations

# 加入預設資料
def add_default_additions(apps, schema_editor):
    additions = apps.get_model('products', 'Additions')
    additions.objects.create(name='加蛋', price=10, is_active=True)
    additions.objects.create(name='加培根', price=15, is_active=True)
    additions.objects.create(name='加蔥花', price=5, is_active=True)
    additions.objects.create(name='加蔬菜', price=10, is_active=True)

def reverse_additions(apps, schema_editor):
    additions = apps.get_model('products', 'Additions')
    additions_data = additions.objects.all()
    additions_data.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_additions_categories_remove_products_stock_and_more'),
    ]

    operations = [
        migrations.RunPython(code=add_default_additions, reverse_code=reverse_additions),
    ]

