# Generated by Django 5.0.6 on 2024-06-13 04:02

import website.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=website.utils.MediaPathAndRename('products/')),
        ),
    ]
